name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the API Docker image
      run: docker build ./api --file ./api/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Frontend Docker image
      run: docker build ./front --file ./front/Dockerfile --tag my-image-name:$(date +%s)
